# Generated by Django 2.1.1 on 2018-12-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='poster',
        ),
    ]
