# Generated by Django 2.1.1 on 2018-12-20 17:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_remove_product_poster'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('goods', django.db.models.manager.Manager()),
            ],
        ),
    ]
