# Generated by Django 2.1.1 on 2018-12-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20181220_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.IntegerField(default=0),
        ),
    ]
